version: "3.9"
services:
  authentication-microservice-api:
    container_name: authentication-microservice-api
    build:
      context: ../Backend
      dockerfile: ../Backend/Microservices/AuthenticationMicroservice/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - authentication-microservice-database
    networks:
      - authentication-microservice-network
    env_file:
      - environment/authentication-microservice/api.env
    volumes:
      - authentication-microservice-logs:/logs

  authentication-microservice-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authentication-microservice-database
    ports: 
      - 1433:1433
    networks: 
      - authentication-microservice-network
    env_file:
      - environment/authentication-microservice/database.env
  
  audio-files-microservice-api:
    container_name: audio-files-microservice-api
    build:
      context: ../Backend
      dockerfile: ../Backend/Microservices/AudioFilesMicroservice/Dockerfile
    ports:
      - 5002:80
    depends_on:
      - audio-files-microservice-database
    networks:
      - audio-files-microservice-network
    env_file:
      - environment/audio-files-microservice/api.env

  audio-files-microservice-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: audio-files-microservice-database
    ports:
      - 1434:1433
    networks:
      - audio-files-microservice-network
    env_file:
      - environment/audio-files-microservice/database.env

networks:
  authentication-microservice-network:
  audio-files-microservice-network:

volumes: 
  authentication-microservice-logs:
  